name: Netlify CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Site
        run: curl -X POST -d '{}' ${{ secrets.NETLIFY_BUILD_HOOK }}
